//
//  ExerciseList.swift
//  ProgressiveOverload_Draft
//
//  Created by Chris on 11/29/15.
//  Copyright © 2015 Chris. All rights reserved.
//

import Foundation

var exerciseList = [
    Exercises(name:"Flat Barbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Flat Dumbbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Incline Barbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Incline Dumbbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Decline Barbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Decline Dumbbell Bench Press",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Flat Chest Press Machine",
        musclesUsed:["Chest"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Incline Chest Press Machine",
        musclesUsed:["Chest"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Decline Chest Press Machine",
        musclesUsed:["Chest"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dips -on parallel bars with slight forward lean",
        musclesUsed:["Chest"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Push-Ups",
        musclesUsed:["Chest"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Flat Dumbbell Flyes",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Incline Dumbbell Flyes",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Decline Dumbbell Flyes",
        musclesUsed:["Chest"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Pec Deck Machine",
        musclesUsed:["Chest"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Crossovers/Cable Flyes",
        musclesUsed:["Chest"],
        requiredEquipment:"Cable",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Pull-Ups",
        musclesUsed:["Back"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Chin-Ups",
        musclesUsed:["Back"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Lat Pull-Downs",
        musclesUsed:["Back"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Bent Over Barbell Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Bent Over Dumbbell Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"T-Bar Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Seated Cable Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Cable",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Chest Supported Barbell Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Chest Supported Dumbbell Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Chest Supported Machine Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Inverted Rows",
        musclesUsed:["Back"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Machine Shrugs",
        musclesUsed:["Back"],
        requiredEquipment:"Barbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Shrugs",
        musclesUsed:["Back"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Seated Overhead Barbell Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Seated Overhead Dumbbell Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Standing Overhead Barbell Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Standing Overhead Dumbbell Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Overhead Machine Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Arnold Press",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Bar",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Machine Upright Rows",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Upright Rows",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Lateral Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Machine Lateral Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Cable Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Front Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Machine Front Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Cable Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Machine Rear Delt Rows",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Machine Rear Delt Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Machine Rear Delt Flyes",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Barbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Rear Delt Rows",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Rear Delt Raises",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Machine Rear Delt Flyes",
        musclesUsed:["Shoulder"],
        requiredEquipment:"Dumbbell Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Front Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Front Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Split Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Split Squats",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Lunges",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Lunges",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Step-Ups",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Step-Ups",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Leg Press",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Machine Squat/Hack Squat",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Leg Extensions",
        musclesUsed:["Quadriceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Romanian Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Romanian Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Straight Leg Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Straight Leg Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Sumo Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Sumo Deadlifts",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Glute-Ham Raises",
        musclesUsed:["Hamstring"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Hyperextensions",
        musclesUsed:["Hamstring"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Pull-Throughs",
        musclesUsed:["Hamstring"],
        requiredEquipment:"Cable",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Good-Mornings",
        musclesUsed:["Hamstring"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Leg Curls",
        musclesUsed:["Hamstring"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Standing Barbell Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Barbell Preacher Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Preacher Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Seated Dumbbell Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Incline Dumbbell Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Hammer Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Concentration Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Curls",
        musclesUsed:["Biceps"],
        requiredEquipment:"Cable",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Biceps Curl Machine",
        musclesUsed:["Biceps"],
        requiredEquipment:"Machine",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dips -on parallel bars,elbows close to body,without forward lean",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Flat Close Grip Bench Press",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Decline Close Grip Bench Press",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Close Grip Push-Ups",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Laying Barbell Triceps Extensions",
        musclesUsed:["Triceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Triceps Extensions",
        musclesUsed:["Triceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Skull Crushers",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Overhead Barbell Triceps Extensions",
        musclesUsed:["Triceps"],
        requiredEquipment:"Barbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Dumbbell Triceps Extensions",
        musclesUsed:["Triceps"],
        requiredEquipment:"Dumbbell",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Cable Press-Downs",
        musclesUsed:["Triceps"],
        requiredEquipment:"Cable",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0]),
    Exercises(name:"Bench Dips",
        musclesUsed:["Triceps"],
        requiredEquipment:"None",
        goalStats:[0,0,0],
        myStats:[0,0,0],
        gainOrMaintain:false,
        history:[NSDate():(0,0)],
        baseline:[(0,0)],
        weightProgression:progressPlan[0])
]
    