//
//  RoutineList.swift
//  ProgressiveOverload_Draft
//
//  Created by Chris on 11/29/15.
//  Copyright © 2015 Chris. All rights reserved.
//

import Foundation

var routineList = [Routines(name:"Full Body Bodyweight",routine:[
        Exercises(name:"Push-Ups",
            musclesUsed:["Chest"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Lat Pull-Downs",
            musclesUsed:["Back"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Leg Press",
            musclesUsed:["Quadriceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Leg Extensions",
            musclesUsed:["Quadriceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Glute-Ham Raises",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Hyperextensions",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Good-Mornings",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Leg Curls",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Hammer Curls",
            musclesUsed:["Biceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Concentration Curls",
            musclesUsed:["Biceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Dips -on parallel bars,elbows close to body,without forward lean",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Flat Close Grip Bench Press",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Decline Close Grip Bench Press",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Close Grip Push-Ups",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Skull Crushers",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Bench Dips",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0])
    ]),
    Routines(name:"Legs", routine:[
        Exercises(name:"Leg Press",
            musclesUsed:["Quadriceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Leg Extensions",
            musclesUsed:["Quadriceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Glute-Ham Raises",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Hyperextensions",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Good-Mornings",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Leg Curls",
            musclesUsed:["Hamstring"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0])
    ]),
    Routines(name:"Arms", routine:[
        Exercises(name:"Hammer Curls",
            musclesUsed:["Biceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Concentration Curls",
            musclesUsed:["Biceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Dips -on parallel bars,elbows close to body,without forward lean",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Flat Close Grip Bench Press",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Decline Close Grip Bench Press",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Close Grip Push-Ups",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Skull Crushers",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Bench Dips",
            musclesUsed:["Triceps"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0])
    ]),
    Routines(name:"FullBody Routine", routine:[
        Exercises(name:"Push Ups",
            musclesUsed:["Pectorals", "Triceps", "Back", "Core"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Sit Ups",
            musclesUsed:["Back", "Core"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Squats",
            musclesUsed:["Glutes", "Calves", "Back", "Core"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Deadlift",
            musclesUsed:["Back", "Triceps", "Shoulders", "Core"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0]),
        Exercises(name:"Pull Ups",
            musclesUsed:["Back", "Biceps", "Pectorals"],
            requiredEquipment:"None",
            goalStats:[0,0,0],
            myStats:[0,0,0],
            gainOrMaintain:false,
            history:[NSDate():(0,0)],
            baseline:[(0,0)],
            weightProgression:progressPlan[0])]
        )
    ]